### ISSUE TITLE
[Feat] - 배터리팩 품질 API 개발

### ISSUE THREAD

**Issue by Hwangwoosam** [HAE-SMARTFACTORY-2/SFaaS-Server#11]
## 🛠 Issue

배터리품질 데이터 관련 API 추가
## 🚀 To-do

- [ ] 시간에 따른 배터리 전압 변화량 API 추가
- [ ] 시간에 따른 배터리 온도 변화량 API 추가
- [ ] 시간에 따른 Soc 상태 변화량 API 추가
- [ ] 시간에 따른 배터리품질 상세 데이터 조회 API 추가
