### ISSUE TITLE
[Feat] 용접 설비 관련 나머지 API 개발

### ISSUE THREAD

**Issue by 0lynny** [HAE-SMARTFACTORY-2/SFaaS-Server#12]
## 🛠 Issue

용접 설비 관련 나머지 API 개발

## 🚀 To-do

- [ ] 용접 길이에 따른 가동시간 추이 API Response 수정
- [ ] 용접 출력 값 비교 API API
- [ ] 용접 예측값 - 실제값 비교 API 구현
