### ISSUE TITLE
[Feat] 시간별 생산량 조회 API 구현 및 품질 RequestPara에 fId 추가

### ISSUE THREAD

**Issue by 0lynny** [HAE-SMARTFACTORY-2/SFaaS-Server#19]
## 🛠 Issue

시간별 생산량 조회 API 구현 및 품질 RequestParam 추가

## 🚀 To-do

- [ ] node-red 를 통한 실시간 데이터 생성 기능 추가
- [ ] 시간별 생산량 조회 API 구현 
- [ ] 품질 RequestParam -> fId 추가
