### ISSUE TITLE
[Feat] 용접 설비 관련 API 구현

### ISSUE THREAD

**Issue by 0lynny** [HAE-SMARTFACTORY-2/SFaaS-Server#9]
## 🛠 Issue

- 용접 설비 관련 API 구현

## 🚀 To-do

- [x] node-red를 통한 생산 데이터 수집
- [x] 용접 설비 데이터 조회 API
- [x] 용접 길이에 따른 가동시간 추이 API
- [ ] 용접 출력 값 비교 API API
- [ ] 용접 예측값 - 실제값 비교 API 구현
- [x] 공장별, 시작 기간 - 끝 기간, 불량/양품, 월/주/일별 추가
